spring.application.name=veterinary-pet-system
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/vet_clinic
spring.datasource.username=root
spring.datasource.password=your_password

# Hibernate (JPA) Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

